Feat/aldroid_tool_improvements (#2)
Updated aldroid with the following:

* only optionally require zipalign

* minor improvements and additional TODOs

* added a start subcommand to start an app by package name on a connected device

* updated help command with tool locations

* default to use aapt2

* updated version

diff --git a/aldroid b/aldroid
--- a/aldroid
+++ b/aldroid
@@ -10,7 +10,7 @@
 # Example Usage: ./aldroid.sh d com.applovin.enterprise.apps.demoapp
 #
 
-VERSION=0.1.0
+VERSION=0.2.0
 
 usage() {
     cat <<EOF
@@ -34,6 +34,14 @@ Pull files for given package name.
   -o <output_directory> Directory in which to store the files. Defaults to /tmp/<package_name>
   --apk          Pull apk(s).
   --obb          Pull obb(s).
+
+usage: aldroid start <package_name>
+Starts the app with the given package name on the connected device.
+
+required tools:
+adb - Android Platform Tools, usually located under ~/Library/Android/sdk/platform-tools/adb
+apktool - Apktool, install via 'brew install apktool'
+apksigner - Android Build Tools, usually located under ~/Library/Android/sdk/build-tools/<version>/apksigner
 EOF
 }
 
@@ -140,11 +148,16 @@ sign_apk() {
     check_keystore
     local debug_keystore=~/.android/debug.keystore
 
-    # Realigns APK so it can be signed
-    echo "Aligning $APK_IN to $APK_OUT..."
-    # -f: overwrite output path if it exists
-    #  4: defines byte-alignment boundaries; must be 4
-    zipalign -f 4 "$APK_IN" "$APK_OUT"
+    # Optionally realign APK
+    if [[ $ALIGN_OPT_SET == true ]]; then
+        echo "Aligning $APK_IN to $APK_OUT..."
+
+        # -f: overwrite output path if it exists
+        #  4: defines byte-alignment boundaries; must be 4
+        zipalign -f 4 "$APK_IN" "$APK_OUT"
+    else
+        cp "$APK_IN" "$APK_OUT"
+    fi
 
     # Signs the APK
     echo "Signing $APK_OUT..."
@@ -198,8 +211,8 @@ pull_apks() {
         echo "Pulled ${APK_REMOTE_PATH##*/} to $OUTPUT_DIRECTORY/${APK_REMOTE_PATH##*/}"
 
         # Add the saved APKs filename to the array
-        # TODO: split into 2 lines for better readability
-        PULLED_APKS+=("$(basename "$APK_REMOTE_PATH")")
+        APK_REMOTE_BASE_NAME="$(basename "$APK_REMOTE_PATH")"
+        PULLED_APKS+=("$APK_REMOTE_BASE_NAME")
     done <<< "$apks"
 
     if [[ ${#PULLED_APKS[@]} -eq 0 ]]; then
@@ -279,6 +292,7 @@ elif ! grep "debug-overrides" "$INPUT_DIRECTORY/res/xml/network_security_config.
     fi
 
     # Set networkSecurityConfig in the Android Manifest if it is not in the application tag
+    # TODO: we should do this first in case they call their network security config something different from network_security_config.xml then we can extract the name and transform that one instead of creating a new one
     if ! grep -E "<application.*?networkSecurityConfig.*?>" "$INPUT_DIRECTORY/AndroidManifest.xml"; then
         sed -E "s/(<application.*)(>)/\1 android\:networkSecurityConfig=\"@xml\/network_security_config\" \2 /" "$INPUT_DIRECTORY/AndroidManifest.xml" > "$INPUT_DIRECTORY/AndroidManifest.xml.tmp"
         mv "$INPUT_DIRECTORY/AndroidManifest.xml.tmp" "$INPUT_DIRECTORY/AndroidManifest.xml"
@@ -513,7 +527,7 @@ push_obbs() {
 start_app() {
     # Verify an argument was provided
     if [ -z $1 ]; then
-        echo "No package name provided to run_app"
+        echo "No package name provided to start_app"
         exit 1
     fi
 
@@ -657,7 +671,8 @@ APK_OPT_SET=false
 OBB_OPT_SET=false
 SPLIT_OPT_SET=false
 INSTALL_OPT_SET=false
-USE_AAPT2=''
+USE_AAPT2='--use-aapt2'
+ALIGN_OPT_SET=false
 
 # Parse options for subcommand
 while getopts "i-:o:" opt; do
@@ -697,11 +712,17 @@ while getopts "i-:o:" opt; do
             split)
                 SPLIT_OPT_SET=true
                 ;;
+            use-aapt)
+                USE_AAPT2=''
+                ;;
             use-aapt2)
                 USE_AAPT2='--use-aapt2'
                 ;;
             install)
                 INSTALL_OPT_SET=true
+                ;;
+            align)
+                ALIGN_OPT_SET=true
                 ;;
             *) # Others - print usage
                 usage
@@ -730,7 +751,7 @@ case $SUBCOMMAND in
         fi
         exit 0
         ;;
-    pull)
+    p|pull)
         # Verify an argument was provided
         if [ -z $1 ]; then
             echo >&2 "ERROR: No package name provided to pull!"
@@ -749,13 +770,24 @@ case $SUBCOMMAND in
 
         exit 0
         ;;
+    s|start)
+        # Verify an argument was provided
+        if [ -z $1 ]; then
+            echo >&2 "ERROR: No package name provided to start!"
+            exit 1
+        fi
+
+        start_app $1
+        exit 0
+        ;;
 # TODO: support an install action which pushes obbs too?
 #    install)
 #        ;;
-# TODO: support pushing a set of obbs with a given package name
+# TODO: support pushing a set of obbs with a given package name, to do that push_obbs should accept an optional parameter or the whole obb code needs to be rewritten to no longer need hard coded path for location
 #    push-obb)
 #        push_obbs $2
 #        ;;
+# TODO: support an action to rebuild a folder with apktool and resign it in case manual edits where necessary
     *) # Undefined - print usage
         usage
         exit 1
