feat/aldroid_sign_command

diff --git a/aldroid b/aldroid
--- a/aldroid
+++ b/aldroid
@@ -46,6 +46,9 @@ Starts the app with the given package name on the connected device.
 usage: aldroid kill <package_name>
 Stops the app with the given package name on the connected device.
 
+usage: aldroid sign <apk_file>
+Signs the given (unsigned) APK in case of manual adjustment.
+
 required tools:
 adb - Android Platform Tools, usually located under ~/Library/Android/sdk/platform-tools/adb
 apktool - Apktool, install via 'brew install apktool'
@@ -891,6 +894,14 @@ case $SUBCOMMAND in
         start_app $1
         exit 0
         ;;
+    sign)
+        # verify input apk was provided
+        if [ -z $1 ]; then
+            echo >&2 "ERROR: please provide input apk!"
+            exit 1
+            APK_OUT=$OUT_OPT_ARG
+        elif [[ -n $OUT_OPT_ARG ]]; then
+            if is_out_path_like_file; then
 # TODO: support an install action which pushes obbs too?
 #    install)
 #        ;;
